# Generated by Django 4.1.2 on 2022-10-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(default='SOME STRING', max_length=256, unique=True),
        ),
    ]
