# Generated by Django 4.1.2 on 2022-10-26 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='SOME STRING', max_length=256, unique=True)),
                ('last_name', models.CharField(default='SOME STRING', max_length=256, unique=True)),
                ('email', models.CharField(default='SOME STRING', max_length=256, unique=True)),
            ],
        ),
    ]
