# Generated by Django 4.1.2 on 2022-10-26 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(default='SOME STRING', max_length=256),
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(default='SOME STRING', max_length=256),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(default='SOME STRING', max_length=256),
        ),
    ]
